[tool.poetry]
name = "confctl"
version = "0.3.1"
description = "Simple configuration management"
authors = ["miphreal <miphreal@gmail.com>"]
license = "MIT"

readme = "README.md"

repository = "https://github.com/miphreal/confctl"

[tool.poetry.scripts]
confctl = "confctl.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
docopt = "^0.6.2"
jinja2 = "^2.11.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
